Repository facebookresearch/CompilerGym, pull requests merged in 2020-12, with the labels that each got.

#6 [README] Improve cold-start description
  README.md
Labels: CLA Signed, Documentation

#7 Fix random_search when max reward < 0
  compiler_gym/bin/random_eval.py
  compiler_gym/random_replay.py
  compiler_gym/random_search.py
Labels: CLA Signed

#13 add note on where the binary works
  README.md
Labels: CLA Signed

#11 Add microbenchmark suite.
  examples/makefile_integration/Makefile
  tests/benchmarks/BUILD
  tests/benchmarks/__init__.py
  tests/benchmarks/bench_test.py
  tests/envs/llvm/BUILD
Labels: CLA Signed

#9 Incremental rewards and native code size
  WORKSPACE
  compiler_gym/envs/compiler_env.py
  compiler_gym/envs/llvm/service/BUILD
  compiler_gym/envs/llvm/service/Benchmark.cc
  compiler_gym/envs/llvm/service/Benchmark.h
  compiler_gym/envs/llvm/service/BenchmarkFactory.cc
  compiler_gym/envs/llvm/service/BenchmarkFactory.h
  compiler_gym/envs/llvm/service/Cost.cc
  compiler_gym/envs/llvm/service/Cost.h
  compiler_gym/envs/llvm/service/LlvmEnvironment.cc
  compiler_gym/envs/llvm/service/LlvmEnvironment.h
  compiler_gym/envs/llvm/service/LlvmService.cc
  compiler_gym/envs/llvm/service/ObservationSpaces.cc
  compiler_gym/envs/llvm/service/ObservationSpaces.h
  compiler_gym/envs/llvm/service/RewardSpaces.cc
  compiler_gym/envs/llvm/service/RewardSpaces.h
  compiler_gym/random_search.py
  compiler_gym/service/connection.py
  compiler_gym/spaces/commandline.py
  compiler_gym/third_party/cBench/BUILD
  compiler_gym/third_party/cBench/BUILD.inactive
  compiler_gym/third_party/ctuning-programs/BUILD.inactive
  compiler_gym/third_party/llvm/BUILD
  compiler_gym/util/RunfilesPath.cc
  compiler_gym/util/logs.py
  compiler_gym/views/observation.py
  docs/source/getting_started.rst
  docs/source/llvm/index.rst
  examples/brute_force_test.py
  examples/sensitivity_analysis/action_sensitivity_analysis.py
  examples/sensitivity_analysis/action_sensitivity_analysis_test.py
  examples/sensitivity_analysis/benchmark_sensitivity_analysis.py
  setup.py
  tests/envs/llvm/BUILD
  tests/envs/llvm/all_actions_single_step_test.py
  tests/envs/llvm/benchmarks_random_actions_test.py
  tests/envs/llvm/fixtures.py
  tests/envs/llvm/fresh_environment_observation_reward_test.py
  tests/envs/llvm/llvm_env_test.py
  tests/envs/llvm/service/ObservationSpacesTest.cc
  tests/envs/llvm/service/RewardSpacesTest.cc
Labels: CLA Signed

#14 Overhaul and improve documentation of the Makefile
  .github/workflows/ci.yaml
  Makefile
  README.md
Labels: CLA Signed

#15 Add a dockerfile for building python wheels
  .github/workflows/pre_commit.yaml
  .pre-commit-config.yaml
  Makefile
  packaging/Dockerfile
Labels: CLA Signed

#17 Add specification for reward and observation spaces
  Makefile
  compiler_gym/bin/manual_env.py
  compiler_gym/bin/service.py
  compiler_gym/envs/compiler_env.py
  compiler_gym/envs/llvm/__init__.py
  compiler_gym/envs/llvm/service/Cost.cc
  compiler_gym/envs/llvm/service/LlvmEnvironment.cc
  compiler_gym/envs/llvm/service/ObservationSpaces.cc
  compiler_gym/envs/llvm/service/ObservationSpaces.h
  compiler_gym/envs/llvm/service/RewardSpaces.cc
  compiler_gym/envs/llvm/service/RewardSpaces.h
  compiler_gym/random_replay.py
  compiler_gym/random_search.py
  compiler_gym/service/connection.py
  compiler_gym/service/proto/compiler_gym_service.proto
  compiler_gym/service/proto2py.py
  compiler_gym/spaces/sequence.py
  compiler_gym/util/flags/env_from_flags.py
  compiler_gym/views/BUILD
  compiler_gym/views/__init__.py
  compiler_gym/views/observation.py
  compiler_gym/views/observation_space_spec.py
  compiler_gym/views/reward.py
  compiler_gym/views/reward_space_spec.py
  docs/source/compiler_gym/views.rst
  docs/source/llvm/index.rst
  examples/brute_force.py
  examples/example_compiler_gym_service/__init__.py
  examples/example_compiler_gym_service/env_tests.py
  examples/sensitivity_analysis/action_sensitivity_analysis.py
  examples/sensitivity_analysis/benchmark_sensitivity_analysis.py
  tests/envs/llvm/BUILD
  tests/envs/llvm/all_actions_single_step_test.py
  tests/envs/llvm/benchmarks_random_actions_test.py
  tests/envs/llvm/fixtures.py
  tests/envs/llvm/fresh_environment_observation_reward_test.py
  tests/envs/llvm/llvm_env_test.py
  tests/envs/llvm/observation_spaces_test.py
  tests/envs/llvm/reward_spaces_test.py
  tests/envs/llvm/service/ObservationSpacesTest.cc
  tests/envs/llvm/service/RewardSpacesTest.cc
Labels: CLA Signed, LLVM

#19 Add version number to python modules
  compiler_gym/__init__.py
  compiler_gym/envs/compiler_env.py
  compiler_gym/envs/llvm/service/BUILD
  compiler_gym/envs/llvm/service/LlvmService.cc
  compiler_gym/envs/llvm/service/LlvmService.h
  compiler_gym/service/proto/__init__.py
  compiler_gym/service/proto/compiler_gym_service.proto
  compiler_gym/util/BUILD
  docs/source/faq.rst
  examples/example_compiler_gym_service/BUILD
  examples/example_compiler_gym_service/env_tests.py
  examples/example_compiler_gym_service/service/BUILD
  examples/example_compiler_gym_service/service/ExampleService.cc
  examples/example_compiler_gym_service/service/ExampleService.h
  tests/BUILD
  tests/envs/llvm/BUILD
  tests/envs/llvm/llvm_env_test.py
  tests/version_test.py
Labels: CLA Signed

#20 Don't redirect service stdout/stderr.
  compiler_gym/service/connection.py
Labels: CLA Signed

#21 Port the getting started tutorial to a Jupyter notebook
  docs/source/getting_started.rst
  examples/getting-started.ipynb
Labels: CLA Signed

#18 Add a make_benchmark() API for LLVM
  BUILD.bazel
  README.md
  compiler_gym/bin/service.py
  compiler_gym/envs/compiler_env.py
  compiler_gym/envs/llvm/BUILD
  compiler_gym/envs/llvm/__init__.py
  compiler_gym/envs/llvm/benchmarks.py
  compiler_gym/envs/llvm/llvm_env.py
  compiler_gym/random_search.py
  compiler_gym/third_party/llvm/BUILD
  compiler_gym/util/tabulate.py
  docs/source/getting_started.rst
  docs/source/index.rst
  docs/source/llvm/api.rst
  setup.py
  tests/envs/llvm/custom_benchmarks_test.py
  tests/envs/llvm/llvm_env_test.py
Labels: CLA Signed

#23 Prevent github actions running twice on PRs
  .github/workflows/ci.yaml
  .github/workflows/pre_commit.yaml
  .github/workflows/release_test.yaml
Labels: CLA Signed

#25 Remove build dependency on absl-py
  .github/workflows/ci.yaml
  compiler_gym/third_party/cBench/BUILD
  compiler_gym/third_party/cBench/BUILD.inactive
  compiler_gym/third_party/cBench/make_llvm_module.py
Labels: CLA Signed

#24 Add a test for gym.make(...) kwargs
  README.md
  tests/envs/llvm/llvm_env_test.py
Labels: CLA Signed

#29 [ci] Allow release-test workflow to be run manually.
  .github/workflows/release_test.yaml
Labels: CLA Signed

#27 [llvm] Use llvm-size to measure .text section size.
  compiler_gym/bin/random_search.py
  compiler_gym/envs/llvm/benchmarks.py
  compiler_gym/envs/llvm/service/BUILD
  compiler_gym/envs/llvm/service/Cost.cc
  compiler_gym/envs/llvm/service/Cost.h
  compiler_gym/envs/llvm/service/LlvmEnvironment.cc
  compiler_gym/envs/llvm/service/LlvmService.cc
  compiler_gym/envs/llvm/service/ObservationSpaces.cc
  compiler_gym/envs/llvm/service/ObservationSpaces.h
  compiler_gym/envs/llvm/service/RewardSpaces.cc
  compiler_gym/envs/llvm/service/RewardSpaces.h
  compiler_gym/random_replay.py
  compiler_gym/random_search.py
  compiler_gym/third_party/llvm/BUILD
  compiler_gym/util/logs.py
  setup.py
  tests/envs/llvm/observation_spaces_test.py
Labels: CLA Signed
