Repository facebookresearch/CompilerGym, pull requests merged in 2021-11, with the labels that each got.

#475 [tests] Remove bind to all addresses in test logic.
  examples/example_compiler_gym_service/env_tests.py
Labels: CLA Signed

#386 [examples] Add LLVM autotuning integrations
  compiler_gym/envs/llvm/compute_observation.py
  examples/.gitignore
  examples/Makefile
  examples/README.md
  examples/example_compiler_gym_service/demo_without_bazel_test.py
  examples/llvm_autotuning/README.md
  examples/llvm_autotuning/__init__.py
  examples/llvm_autotuning/autotuners/__init__.py
  examples/llvm_autotuning/autotuners/greedy.py
  examples/llvm_autotuning/autotuners/greedy_test.py
  examples/llvm_autotuning/autotuners/nevergrad_.py
  examples/llvm_autotuning/autotuners/nevergrad_test.py
  examples/llvm_autotuning/autotuners/opentuner_.py
  examples/llvm_autotuning/autotuners/opentuner_test.py
  examples/llvm_autotuning/autotuners/random_.py
  examples/llvm_autotuning/autotuners/random_test.py
  examples/llvm_autotuning/benchmarks.py
  examples/llvm_autotuning/config/autotuner/greedy.yaml
  examples/llvm_autotuning/config/autotuner/nevergrad.yaml
  examples/llvm_autotuning/config/autotuner/opentuner.yaml
  examples/llvm_autotuning/config/autotuner/random.yaml
  examples/llvm_autotuning/config/benchmarks/cbench.yaml
  examples/llvm_autotuning/config/benchmarks/csmith-50.yaml
  examples/llvm_autotuning/config/default.yaml
  examples/llvm_autotuning/config/executor/debug.yaml
  examples/llvm_autotuning/config/executor/local.yaml
  examples/llvm_autotuning/config/executor/noop.yaml
  examples/llvm_autotuning/config/executor/slurm.yaml
  examples/llvm_autotuning/count_autotuner_loc.sh
  examples/llvm_autotuning/executor.py
  examples/llvm_autotuning/executor_test.py
  examples/llvm_autotuning/experiment.py
  examples/llvm_autotuning/info.py
  examples/llvm_autotuning/just_keep_going_env.py
  examples/llvm_autotuning/optimization_target.py
  examples/llvm_autotuning/tune.py
  examples/requirements.txt
  examples/sensitivity_analysis/action_sensitivity_analysis_test.py
  examples/setup.py
  tests/llvm/datasets/csmith_test.py
  tests/llvm/fork_env_test.py
  tests/llvm/fresh_environment_observation_reward_test.py
Labels: CLA Signed

#476 [examples] Add LLVM reinforcement learning wrappers.
  examples/llvm_rl/__init__.py
  examples/llvm_rl/autophase_wrappers.py
  examples/llvm_rl/autophase_wrappers_test.py
Labels: CLA Signed

#477 Enhance Loop Unroller
  examples/example_unrolling_service/loop_unroller/BUILD
  examples/example_unrolling_service/loop_unroller/README.md
  examples/example_unrolling_service/loop_unroller/loop_unroller.cc
  examples/example_unrolling_service/service_py/BUILD
  examples/example_unrolling_service/service_py/example_service.py
Labels: CLA Signed

#486 [Makefile] Run `pip uninstall` before `pip install`.
  Makefile
Labels: CLA Signed

#489 [llvm] Don't use fully-qualified module imports for codegen scripts.
  compiler_gym/envs/llvm/service/passes/BUILD
  compiler_gym/envs/llvm/service/passes/config.py
  compiler_gym/envs/llvm/service/passes/extract_passes_from_llvm_source_tree.py
  compiler_gym/envs/llvm/service/passes/filter_action_space.py
  compiler_gym/envs/llvm/service/passes/make_action_space_genfiles.py
Labels: CLA Signed, Testing & Tooling

#492 [docs] Add a favicon for CompilerGym documentation site.
  Makefile
  docs/source/_static/img/favicon.png
  docs/source/conf.py
  www/frontends/compiler_gym/src/compilerGym-logo.png
  www/frontends/compiler_gym/src/logo.svg
  www/set_api_ip.sh
Labels: Documentation, CLA Signed

#496 [ci] Add a step to empty the build cache.
  .github/workflows/ci.yaml
Labels: CLA Signed
