Repository facebookresearch/CompilerGym, pull requests merged in 2021-04, with the labels that each got.

#165 Release v0.1.7.
  .github/workflows/ci.yaml
  CHANGELOG.md
  README.md
  VERSION
  compiler_gym/util/runfiles_path.py
  docs/source/_static/img/datasets.png
  docs/source/_static/img/programl.png
  docs/source/llvm/index.rst
  packaging/Dockerfile
  requirements_pre_commit.txt
  tests/BUILD
  tests/pytest_plugins/common.py
  tests/version_test.py
Labels: CLA Signed

#168 Fix missing python package dependencies for compiler_gym.leaderboard
  .github/workflows/ci.yaml
  compiler_gym/bin/validate.py
  compiler_gym/envs/compiler_env.py
  compiler_gym/leaderboard/llvm_instcount.py
  compiler_gym/util/statistics.py
  compiler_gym/util/timer.py
  leaderboard/llvm_instcount/e_greedy/BUILD
  leaderboard/llvm_instcount/e_greedy/README.md
  leaderboard/llvm_instcount/random_search/BUILD
  leaderboard/requirements.txt
  requirements.txt
  tests/leaderboard/llvm_instcount_test.py
  tests/util/timer_test.py
Labels: CLA Signed

#169 Move benchmarks into top-level directory
  benchmarks/BUILD
  benchmarks/bench_test.py
  benchmarks/parallelization_load_test.py
  benchmarks/parallelization_load_test_test.py
  tests/BUILD
  tests/benchmarks/__init__.py
Labels: CLA Signed

#170 [readme] Add an "open in colab" badge to readme.
  README.md
Labels: CLA Signed

#171 [llvm] Strip module and source IDs in benchmarks.
  compiler_gym/envs/llvm/service/Benchmark.cc
  compiler_gym/envs/llvm/service/Benchmark.h
  tests/llvm/BUILD
  tests/llvm/module_id_test.py
Labels: CLA Signed, Datasets, LLVM

#172 [llvm] Silence clang warnings during cost calculation.
  compiler_gym/envs/llvm/service/Cost.cc
Labels: CLA Signed, LLVM

#177 [util] Use more granular locking for download().
  compiler_gym/util/download.py
Labels: CLA Signed

#173 New Dataset API patchset 1
  CHANGELOG.md
  benchmarks/BUILD
  compiler_gym/bin/manual_env.py
  compiler_gym/envs/llvm/service/Cost.cc
  compiler_gym/service/connection.py
  compiler_gym/service/proto/compiler_gym_service.proto
  compiler_gym/util/BUILD
  compiler_gym/util/decorators.py
  examples/example_compiler_gym_service/service_cc/ExampleService.cc
  examples/example_compiler_gym_service/service_cc/ExampleService.h
  leaderboard/llvm_instcount/e_greedy/BUILD
  tests/llvm/llvm_env_test.py
  tests/llvm/multiprocessing_test.py
  tests/llvm/service_connection_test.py
Labels: CLA Signed

#176 Remove the --ls_benchmark and --dataset flags.
  compiler_gym/bin/BUILD
  compiler_gym/bin/manual_env.py
  compiler_gym/bin/random_search.py
  compiler_gym/bin/validate.py
  compiler_gym/util/flags/BUILD
  compiler_gym/util/flags/dataset.py
  compiler_gym/util/flags/ls_benchmark.py
  tests/bin/datasets_bin_test.py
  tests/bin/validate_bin_test.py
Labels: CLA Signed

#178 [rpc] Use a more terse name for service working directories.
  compiler_gym/service/connection.py
Labels: CLA Signed

#141 Leaderboard implementation of tabular Q
  README.md
  examples/BUILD
  examples/tabular_q.py
  leaderboard/llvm_instcount/tabular_q/BUILD
  leaderboard/llvm_instcount/tabular_q/README.md
  leaderboard/llvm_instcount/tabular_q/results-H10-N5000.csv
  leaderboard/llvm_instcount/tabular_q/results-H5-N2000.csv
  leaderboard/llvm_instcount/tabular_q/tabular_q_eval.py
  leaderboard/llvm_instcount/tabular_q/tabular_q_test.py
Labels: Bug, CLA Signed

#183 Update README.md
  README.md
Labels: CLA Signed

#184 [util] Make download() accept a list of redundant URLS.
  compiler_gym/util/download.py
Labels: CLA Signed

#186 [util] Add a filesystem module.
  compiler_gym/util/BUILD
  compiler_gym/util/filesystem.py
  tests/util/BUILD
  tests/util/filesystem_test.py
Labels: CLA Signed

#187 [env] Replace `logging_level` init arg with `logger`.
  compiler_gym/envs/compiler_env.py
  tests/compiler_env_test.py
  tests/llvm/llvm_env_test.py
Labels: CLA Signed

#188 [tests] Filter noisy warnings on install-test.
  Makefile
  tox.ini
Labels: CLA Signed

#189 [env] Add initial observations to StartSession calls.
  compiler_gym/envs/compiler_env.py
  compiler_gym/envs/llvm/service/LlvmService.cc
  compiler_gym/envs/llvm/service/LlvmSession.h
  compiler_gym/service/proto/compiler_gym_service.proto
  examples/example_compiler_gym_service/service_cc/ExampleService.cc
  examples/example_compiler_gym_service/service_cc/ExampleService.h
  examples/example_compiler_gym_service/service_py/example_service.py
Labels: CLA Signed

#194 Minor fixups split out from dataset overhaul.
  Makefile
  benchmarks/BUILD
  benchmarks/bench_test.py
  benchmarks/parallelization_load_test_test.py
  docs/source/getting_started.rst
  examples/BUILD
  examples/actor_critic_test.py
  examples/sensitivity_analysis/BUILD
  examples/sensitivity_analysis/action_sensitivity_analysis_test.py
  examples/sensitivity_analysis/benchmark_sensitivity_analysis_test.py
  examples/tabular_q_test.py
  leaderboard/llvm_instcount/e_greedy/e_greedy_test.py
  leaderboard/llvm_instcount/random_search/BUILD
  leaderboard/llvm_instcount/random_search/random_search_test.py
  tests/bin/BUILD
  tests/bin/datasets_bin_test.py
  tests/bin/validate_bin_test.py
  tests/leaderboard/llvm_instcount_test.py
  tests/pytest_plugins/common.py
Labels: CLA Signed

#196 [docs] Add a table of feature stability.
  CONTRIBUTING.md
  README.md
  docs/requirements.txt
  docs/source/about.rst
  docs/source/conf.py
Labels: CLA Signed

#197 [util] Use atomic_write_path() for download().
  compiler_gym/util/download.py
Labels: CLA Signed

#190 [datasets-overhaul #1] Add a new Benchmark class.
  compiler_gym/datasets/BUILD
  compiler_gym/datasets/__init__.py
  compiler_gym/datasets/benchmark.py
  tests/datasets/BUILD
  tests/datasets/benchmark_test.py
Labels: CLA Signed

#191 [datasets-overhaul #2] Add a new Dataset class.
  compiler_gym/bin/BUILD
  compiler_gym/datasets/BUILD
  compiler_gym/datasets/__init__.py
  compiler_gym/datasets/dataset.py
  compiler_gym/envs/BUILD
  compiler_gym/envs/llvm/BUILD
  tests/datasets/BUILD
  tests/datasets/dataset_test.py
Labels: CLA Signed

#192 [datasets-overhaul #3] Add Dataset helper subclasses.
  compiler_gym/datasets/BUILD
  compiler_gym/datasets/__init__.py
  compiler_gym/datasets/files_dataset.py
  compiler_gym/datasets/tar_dataset.py
  tests/datasets/BUILD
  tests/datasets/files_dataset_test.py
Labels: CLA Signed

#195 [datasets-overhaul #1.5] Update make_benchmark() to use the new Benchmark class.
  compiler_gym/envs/compiler_env.py
  compiler_gym/envs/llvm/BUILD
  compiler_gym/envs/llvm/__init__.py
  compiler_gym/envs/llvm/llvm_benchmark.py
  compiler_gym/envs/llvm/llvm_env.py
  compiler_gym/envs/llvm/service/Cost.cc
  compiler_gym/envs/llvm/service/LlvmSession.cc
  compiler_gym/third_party/cBench/BUILD
  compiler_gym/third_party/cBench/make_llvm_module.py
  compiler_gym/third_party/llvm/BUILD
  compiler_gym/third_party/llvm/__init__.py
  tests/llvm/BUILD
  tests/llvm/custom_benchmarks_test.py
  tests/llvm/invalid_ir.ll
Labels: CLA Signed

#198 [datasets] Add Dataset __getitem__, __iter__, and __len__.
  compiler_gym/datasets/dataset.py
  compiler_gym/datasets/files_dataset.py
  compiler_gym/datasets/tar_dataset.py
  tests/datasets/dataset_test.py
  tests/datasets/files_dataset_test.py
Labels: CLA Signed

#199 Fix s/benchamrk/benchmark/ typo.
  benchmarks/bench_test.py
  benchmarks/parallelization_load_test_test.py
  compiler_gym/datasets/files_dataset.py
  compiler_gym/envs/llvm/llvm_rewards.py
Labels: CLA Signed

#200 [datasets] Add a Datasets class for managing datasets.
  compiler_gym/datasets/BUILD
  compiler_gym/datasets/__init__.py
  compiler_gym/datasets/dataset.py
  compiler_gym/datasets/datasets.py
  compiler_gym/datasets/files_dataset.py
  tests/datasets/BUILD
  tests/datasets/datasets_test.py
  tests/datasets/files_dataset_test.py
  tests/llvm/BUILD
  tests/llvm/datasets_test.py
Labels: CLA Signed

#201 Add CompilerEnv.datasets member variable.
  compiler_gym/envs/compiler_env.py
Labels: CLA Signed

#203 Move DefaultRewardFromObservation into spaces namespace.
  compiler_gym/envs/compiler_env.py
  compiler_gym/spaces/__init__.py
  compiler_gym/spaces/reward.py
Labels: CLA Signed

#212 [CONTRIBUTING] Add a note about updating to latest version.
  CONTRIBUTING.md
Labels: CLA Signed

#204 [env] Add a SessionNotFound error.
  compiler_gym/envs/compiler_env.py
  compiler_gym/envs/llvm/service/LlvmService.cc
  compiler_gym/service/__init__.py
  compiler_gym/service/connection.py
  examples/example_compiler_gym_service/env_tests.py
  examples/example_compiler_gym_service/service_cc/BUILD
  examples/example_compiler_gym_service/service_cc/ExampleService.cc
  examples/example_compiler_gym_service/service_py/example_service.py
Labels: CLA Signed

#205 [llvm] Port some of the LLVM datasets to the new interface.
  compiler_gym/envs/llvm/BUILD
  compiler_gym/envs/llvm/datasets/BUILD
  compiler_gym/envs/llvm/datasets/__init__.py
  compiler_gym/envs/llvm/llvm_env.py
  setup.py
  tests/llvm/datasets/BUILD
  tests/llvm/datasets/github_test.py
Labels: CLA Signed

#206 [llvm] Add a new POJ-104 implementation.
  compiler_gym/envs/llvm/datasets/BUILD
  compiler_gym/envs/llvm/datasets/__init__.py
  compiler_gym/envs/llvm/datasets/poj104.py
  tests/llvm/datasets/BUILD
  tests/llvm/datasets/poj104_test.py
Labels: CLA Signed

#207 [llvm] Add Csmith and llvm-stress benchmark generators.
  compiler_gym/envs/llvm/datasets/BUILD
  compiler_gym/envs/llvm/datasets/__init__.py
  compiler_gym/envs/llvm/datasets/csmith.py
  compiler_gym/envs/llvm/datasets/llvm_stress.py
  compiler_gym/envs/llvm/datasets/poj104.py
  tests/llvm/datasets/BUILD
  tests/llvm/datasets/csmith_test.py
  tests/llvm/datasets/llvm_stress_test.py
Labels: CLA Signed

#208 [llvm] Add a CLgen dataset.
  compiler_gym/envs/llvm/datasets/BUILD
  compiler_gym/envs/llvm/datasets/__init__.py
  compiler_gym/envs/llvm/datasets/clgen.py
  tests/llvm/datasets/BUILD
  tests/llvm/datasets/clgen_test.py
  tests/requirements.txt
Labels: CLA Signed

#210 [llvm] Add the AnghaBench dataset.
  compiler_gym/envs/llvm/datasets/BUILD
  compiler_gym/envs/llvm/datasets/__init__.py
  compiler_gym/envs/llvm/datasets/anghabench.py
  tests/llvm/datasets/BUILD
  tests/llvm/datasets/anghabench_test.py
Labels: CLA Signed

#211 [llvm] Port the cBench dataset to the new API.
  compiler_gym/envs/llvm/datasets/BUILD
  compiler_gym/envs/llvm/datasets/__init__.py
  compiler_gym/envs/llvm/datasets/cbench.py
  tests/llvm/datasets/BUILD
  tests/llvm/datasets/cbench_test.py
  tests/llvm/datasets/cbench_validate_test.py
  tests/llvm/datasets/llvm_datasets_test.py
Labels: CLA Signed

#214 [datasets] Tighten the requirements of benchmark name regex.
  compiler_gym/datasets/benchmark.py
  tests/datasets/benchmark_test.py
Labels: CLA Signed

#220 [Makefile] Remove redundant test dataset rule.
  Makefile
Labels: CLA Signed

#218 [datasets] Fix llvm-stress test.
  tests/llvm/datasets/llvm_stress_test.py
Labels: CLA Signed

#213 Encourage open sourcing of leaderboard submissions
  CONTRIBUTING.md
Labels: CLA Signed

#217 Use pydantic for CompilerEnvState.
  compiler_gym/BUILD
  compiler_gym/__init__.py
  compiler_gym/compiler_env_state.py
  compiler_gym/datasets/BUILD
  compiler_gym/datasets/benchmark.py
  compiler_gym/datasets/dataset.py
  compiler_gym/datasets/datasets.py
  compiler_gym/datasets/uri.py
  compiler_gym/envs/compiler_env.py
  compiler_gym/envs/llvm/legacy_datasets.py
  compiler_gym/envs/llvm/llvm_env.py
  compiler_gym/leaderboard/llvm_instcount.py
  compiler_gym/requirements.txt
  compiler_gym/validation_error.py
  compiler_gym/validation_result.py
  tests/compiler_env_state_test.py
  tests/datasets/benchmark_test.py
  tests/llvm/benchmark_semantics_validation_test.py
  tests/validation_result_test.py
Labels: CLA Signed

#221 Update docs for the new dataset API.
  README.md
  compiler_gym/bin/datasets.py
  compiler_gym/bin/manual_env.py
  compiler_gym/bin/random_search.py
  compiler_gym/bin/service.py
  compiler_gym/bin/validate.py
  compiler_gym/envs/llvm/llvm_env.py
  compiler_gym/third_party/inst2vec/__init__.py
  docs/source/_static/img/datasets.png
  docs/source/compiler_gym/datasets.rst
  docs/source/compiler_gym/service.rst
  docs/source/getting_started.rst
  docs/source/llvm/index.rst
  examples/getting-started.ipynb
Labels: CLA Signed

#223 [llvm] Add a load test for download_llvm_files().
  compiler_gym/envs/llvm/datasets/csmith.py
  compiler_gym/third_party/llvm/__init__.py
  tests/llvm/BUILD
  tests/llvm/download_llvm_test.py
  tests/pytest_plugins/BUILD
  tests/pytest_plugins/common.py
Labels: CLA Signed

#226 Relax the pip dependency versions.
  compiler_gym/requirements.txt
Labels: CLA Signed

#228 Make CompilerEnv.observation_space a gym.Space.
  compiler_gym/bin/manual_env.py
  compiler_gym/envs/compiler_env.py
  docs/source/getting_started.rst
  examples/getting-started.ipynb
  examples/random_walk.py
  tests/llvm/BUILD
  tests/llvm/gym_interface_compatability.py
  tests/llvm/llvm_env_test.py
  tests/llvm/observation_spaces_test.py
Labels: CLA Signed

#229 [benchmarks] Add example C++/Python micro-benchmarks.
  benchmarks/BUILD
  benchmarks/bench_test.py
  examples/example_compiler_gym_service/BUILD
  examples/example_compiler_gym_service/__init__.py
  tests/pytest_plugins/llvm.py
Labels: CLA Signed

#234 Use "." name prefix for hidden lockfiles
  compiler_gym/envs/llvm/legacy_datasets.py
  compiler_gym/util/download.py
Labels: CLA Signed

#233 Add automated deprecation warnings to the Dataset class.
  compiler_gym/datasets/dataset.py
  compiler_gym/datasets/datasets.py
  compiler_gym/datasets/tar_dataset.py
  compiler_gym/envs/llvm/datasets/__init__.py
  compiler_gym/envs/llvm/datasets/cbench.py
  compiler_gym/envs/llvm/datasets/csmith.py
  compiler_gym/envs/llvm/datasets/poj104.py
  tests/datasets/dataset_test.py
  tests/datasets/datasets_test.py
  tests/llvm/datasets/cbench_test.py
Labels: CLA Signed

#232 Improvements to documentation
  README.md
  compiler_gym/compiler_env_state.py
  compiler_gym/datasets/benchmark.py
  compiler_gym/datasets/dataset.py
  compiler_gym/datasets/datasets.py
  compiler_gym/datasets/files_dataset.py
  compiler_gym/datasets/tar_dataset.py
  compiler_gym/envs/compiler_env.py
  compiler_gym/envs/llvm/datasets/__init__.py
  compiler_gym/envs/llvm/datasets/csmith.py
  compiler_gym/envs/llvm/datasets/llvm_stress.py
  compiler_gym/envs/llvm/legacy_datasets.py
  compiler_gym/envs/llvm/llvm_env.py
  compiler_gym/spaces/commandline.py
  compiler_gym/util/debug_util.py
  compiler_gym/util/thread_pool.py
  compiler_gym/validation_result.py
  docs/source/compiler_gym/datasets.rst
  docs/source/compiler_gym/service.rst
  docs/source/getting_started.rst
  docs/source/llvm/api.rst
  docs/source/llvm/index.rst
  examples/getting-started.ipynb
  tests/datasets/dataset_test.py
  tests/llvm/BUILD
Labels: CLA Signed

#237 Report and upload pytest coverage report.
  .github/workflows/ci.yaml
  .gitignore
  Makefile
  tests/requirements.txt
Labels: CLA Signed

#236 Use pydantic models and add CompilerEnvState{Reader,Writer}
  compiler_gym/BUILD
  compiler_gym/__init__.py
  compiler_gym/bin/validate.py
  compiler_gym/compiler_env_state.py
  compiler_gym/envs/compiler_env.py
  compiler_gym/leaderboard/llvm_instcount.py
  compiler_gym/service/connection.py
  compiler_gym/validation_error.py
  compiler_gym/validation_result.py
  docs/source/compiler_gym/compiler_gym.rst
  tests/BUILD
  tests/bin/validate_bin_test.py
  tests/compiler_env_state_test.py
  tests/llvm/llvm_env_test.py
  tests/llvm/validation_regression_test.py
  tests/validation_result_test.py
Labels: CLA Signed

#241 Release v0.1.8
  CHANGELOG.md
  VERSION
  compiler_gym/envs/compiler_env.py
  compiler_gym/envs/llvm/datasets/csmith.py
  tests/llvm/datasets/llvm_stress_test.py
Labels: CLA Signed
