Repository facebookresearch/CompilerGym, pull requests merged in 2021-09, with the labels that each got.

#361 [www] Package the Flask app as a Docker container
  Makefile
  packaging/Dockerfile
  packaging/container_init.sh
  www/Dockerfile
  www/requirements.txt
  www/set_api_ip.sh
  www/www.py
Labels: CLA Signed

#359 [docs] Add a new "Environments" section to docs.
  docs/source/index.rst
Labels: CLA Signed

#376 [www] Update the version of the tar package.
  www/frontends/compiler_gym/package-lock.json
Labels: CLA Signed

#378 Release v0.1.10 (2021-09-08)
  CHANGELOG.md
  VERSION
  docs/source/index.rst
Labels: CLA Signed

#379 Small documentation improvements for build dependencies
  INSTALL.md
  packaging/Dockerfile
Labels: CLA Signed

#384 Use `with` statement in place of try/finally for envs.
  benchmarks/parallelization_load_test.py
  compiler_gym/bin/datasets.py
  compiler_gym/bin/random_replay.py
  compiler_gym/bin/random_search.py
  compiler_gym/bin/service.py
  compiler_gym/bin/validate.py
  compiler_gym/leaderboard/llvm_instcount.py
  compiler_gym/random_replay.py
  compiler_gym/random_search.py
  compiler_gym/util/flags/env_from_flags.py
  compiler_gym/validate.py
  docs/source/llvm/index.rst
  examples/actor_critic.py
  examples/brute_force.py
  examples/explore.py
  examples/random_walk.py
  examples/random_walk_test.py
  examples/sensitivity_analysis/action_sensitivity_analysis.py
  examples/sensitivity_analysis/benchmark_sensitivity_analysis.py
  examples/tabular_q.py
  tests/bin/service_bin_test.py
  tests/compiler_env_test.py
  tests/fuzzing/llvm_random_actions_fuzz_test.py
  tests/llvm/all_benchmarks_init_close_test.py
  tests/llvm/custom_benchmarks_test.py
  tests/llvm/datasets/anghabench_test.py
  tests/llvm/datasets/chstone_test.py
  tests/llvm/datasets/clgen_test.py
  tests/llvm/datasets/csmith_test.py
  tests/llvm/datasets/github_test.py
  tests/llvm/datasets/llvm_datasets_test.py
  tests/llvm/datasets/llvm_stress_test.py
  tests/llvm/datasets/poj104_test.py
  tests/llvm/gym_interface_compatability.py
  tests/llvm/llvm_env_test.py
  tests/llvm/multiprocessing_test.py
  tests/llvm/service_connection_test.py
  tests/llvm/threading_test.py
  tests/llvm/validate_test.py
  tests/pytest_plugins/llvm.py
  tests/random_search_test.py
  tests/service/connection_test.py
  tests/wrappers/core_wrappers_test.py
Labels: CLA Signed

#390 [tests] Fix gym compatibility test.
  tests/llvm/BUILD
  tests/llvm/gym_interface_compatability.py
Labels: CLA Signed

#387 Make random_search() return a CompilerEnv.
  compiler_gym/bin/random_search.py
  compiler_gym/random_search.py
  tests/random_search_test.py
Labels: CLA Signed

#388 [www] UI implements api v4
  www/frontends/compiler_gym/src/App.js
  www/frontends/compiler_gym/src/api/ApiService.js
  www/frontends/compiler_gym/src/assets/scss/searchtree.scss
  www/frontends/compiler_gym/src/components/Navbars/ActionsNavbar.js
  www/frontends/compiler_gym/src/components/Sections/ControlsContainer.js
  www/frontends/compiler_gym/src/components/Sections/ObservationsContainer.js
  www/frontends/compiler_gym/src/components/Sections/RewardHistoryChart.js
  www/frontends/compiler_gym/src/components/StateVisualizations/AutophaseHistoricalChart.js
  www/frontends/compiler_gym/src/components/StateVisualizations/AutophaseStateContainer.js
  www/frontends/compiler_gym/src/components/StateVisualizations/InstCountsHistoricalChart.js
  www/frontends/compiler_gym/src/components/StateVisualizations/InstcountsStateContainer.js
  www/frontends/compiler_gym/src/context/ApiContext.js
  www/frontends/compiler_gym/src/utils/ActionsDict.js
  www/frontends/compiler_gym/src/utils/Helpers.js
  www/www.py
Labels: CLA Signed, www

#395 [www] Update npm dependencies.
  www/frontends/compiler_gym/package-lock.json
Labels: CLA Signed

#392 Overhaul CI workflows to improve efficiency
  .github/actions/install-build-dependencies/action.yaml
  .github/actions/install-runtime-dependencies/action.yaml
  .github/workflows/ci.yaml
  .github/workflows/sanitizers.yaml
  Makefile
  benchmarks/BUILD
  compiler_gym/BUILD
  compiler_gym/bin/BUILD
  compiler_gym/util/flags/BUILD
  compiler_gym/util/flags/episode_length.py
  compiler_gym/util/flags/episodes.py
  compiler_gym/util/flags/learning_rate.py
  examples/BUILD
  examples/actor_critic.py
  examples/brute_force.py
  examples/explore.py
  examples/explore_test.py
  examples/sensitivity_analysis/BUILD
  examples/sensitivity_analysis/action_sensitivity_analysis.py
  examples/sensitivity_analysis/benchmark_sensitivity_analysis.py
  examples/tabular_q.py
  tests/bin/manual_env_bin_test.py
  tests/llvm/BUILD
  tests/llvm/datasets_pickle_test.py
Labels: CLA Signed

#400 [tests] Qualify temporary directory with username.
  Makefile
  benchmarks/bench_test.py
  tests/test_main.py
Labels: CLA Signed

#402 Mark a couple of flaky tests as such.
  tests/llvm/datasets/csmith_test.py
  tests/llvm/threading_test.py
  tests/requirements.txt
  tests/test_main.py
Labels: CLA Signed, Testing & Tooling

#404 [gcc] Make a test resilient to auto-generated number value.
  tests/gcc/gcc_env_test.py
Labels: CLA Signed, GCC

#398 Replace subprocess::Popen() with boost::process
  .github/workflows/coverage.yaml
  benchmarks/BUILD
  compiler_gym/envs/gcc/datasets/csmith.py
  compiler_gym/envs/llvm/datasets/cbench.py
  compiler_gym/envs/llvm/datasets/csmith.py
  compiler_gym/envs/llvm/llvm_env.py
  compiler_gym/envs/llvm/service/BUILD
  compiler_gym/envs/llvm/service/Benchmark.cc
  compiler_gym/envs/llvm/service/Benchmark.h
  compiler_gym/envs/llvm/service/Cost.cc
  compiler_gym/envs/llvm/service/LlvmSession.cc
  compiler_gym/service/proto/__init__.py
  compiler_gym/service/proto/compiler_gym_service.proto
  compiler_gym/util/BUILD
  compiler_gym/util/Subprocess.cc
  compiler_gym/util/Subprocess.h
  docs/source/cc/compiler_gym/util.rst
  docs/source/rpc.rst
  tests/llvm/BUILD
  tests/llvm/runtime_test.py
  tests/util/SubprocessTest.cc
Labels: CLA Signed

#405 Add a standalone binary to compute LLMV observations
  .github/workflows/ci.yaml
  compiler_gym/envs/llvm/BUILD
  compiler_gym/envs/llvm/__init__.py
  compiler_gym/envs/llvm/compute_observation.py
  compiler_gym/envs/llvm/service/BUILD
  compiler_gym/envs/llvm/service/Benchmark.cc
  compiler_gym/envs/llvm/service/Benchmark.h
  compiler_gym/envs/llvm/service/ComputeObservation.cc
  compiler_gym/envs/llvm/service/LlvmSession.cc
  compiler_gym/envs/llvm/service/LlvmSession.h
  compiler_gym/envs/llvm/service/Observation.cc
  compiler_gym/envs/llvm/service/Observation.h
  docs/source/cc/compiler_gym/envs/llvm/service.rst
  docs/source/compiler_gym/envs/gcc.rst
  docs/source/index.rst
  docs/source/llvm/api.rst
  setup.py
  tests/llvm/BUILD
  tests/llvm/compute_observation_test.py
Labels: CLA Signed, LLVM

#410 Add a citation to our preprint
  CITATION.cff
  README.md
  packaging/set_version.sh
Labels: CLA Signed

#409 Disable flaky plugin success reports.
  Makefile
  tests/test_main.py
Labels: CLA Signed

#413 [tests] Add implicit psutil package dependency.
  tests/requirements.txt
Labels: CLA Signed

#397 [UI] Added historical chart for single observations
  www/frontends/compiler_gym/public/index.html
  www/frontends/compiler_gym/src/assets/scss/highcharts.scss
  www/frontends/compiler_gym/src/components/Navbars/ActionsNavbar.js
  www/frontends/compiler_gym/src/components/Sections/ControlsContainer.js
  www/frontends/compiler_gym/src/components/StateVisualizations/AutophaseHistoricalChart.js
  www/frontends/compiler_gym/src/components/StateVisualizations/InstCountsHistoricalChart.js
  www/frontends/compiler_gym/src/components/StateVisualizations/ModalSingleChart.js
  www/frontends/compiler_gym/src/components/StateVisualizations/SparkLineTable.js
Labels: CLA Signed, www

#417 Add missing license headers.
  CITATION.cff
  packaging/set_version.sh
Labels: CLA Signed

#416 Automated npm package version audit
  www/frontends/compiler_gym/package-lock.json
  www/frontends/compiler_gym/package.json
Labels: CLA Signed

#418 [leaderboard] Change benchmarks execution to Round Robin
  compiler_gym/leaderboard/llvm_instcount.py
Labels: CLA Signed

#414 [Documentation] Improve instructions for installing pre-commit deps.
  .pre-commit-config.yaml
  INSTALL.md
Labels: CLA Signed

#419 [ci] Overhaul and simplify the pip install test
  .github/workflows/pip_install_test.yaml
  .github/workflows/release_test.yaml
Labels: CLA Signed, Testing & Tooling

#411 Add a GitHub actions workflow to build release binaries
  .github/actions/install-build-dependencies/action.yaml
  .github/workflows/build.yaml
  Makefile
  compiler_gym/envs/llvm/llvm_benchmark.py
Labels: CLA Signed, Testing & Tooling

#415 Improve GCC env docker compatibility
  .github/workflows/ci.yaml
  compiler_gym/envs/compiler_env.py
  compiler_gym/envs/gcc/gcc_env.py
  compiler_gym/service/runtime/CreateAndRunCompilerGymServiceImpl.h
  tests/gcc/datasets/anghabench_test.py
  tests/gcc/datasets/csmith_test.py
  tests/gcc/gcc_env_test.py
  tests/pytest_plugins/gcc.py
Labels: CLA Signed

#421 [ci] Fix Linux test action for running GCC tests without docker.
  .github/workflows/ci.yaml
Labels: CLA Signed

#420 Test fixes and improvements
  Makefile
  compiler_gym/envs/compiler_env.py
  tests/bin/BUILD
  tests/llvm/BUILD
  tests/llvm/all_actions_single_step_test.py
  tests/llvm/fresh_environment_observation_reward_test.py
  tests/llvm/gvn_sink_test.py
  tests/llvm/multiprocessing_test.py
  tests/llvm/observation_spaces_test.py
Labels: CLA Signed

#423 [env] Wrap all RPC calls in reset() in retry loop.
  compiler_gym/envs/compiler_env.py
Labels: CLA Signed

#298 [loop_tool] Add integration and tests
  .github/workflows/ci.yaml
  Makefile
  compiler_gym/envs/BUILD
  compiler_gym/envs/__init__.py
  compiler_gym/envs/loop_tool/BUILD
  compiler_gym/envs/loop_tool/__init__.py
  compiler_gym/envs/loop_tool/loop_tool_env.py
  compiler_gym/envs/loop_tool/service/BUILD
  compiler_gym/envs/loop_tool/service/compiler_gym-loop_tool-service
  compiler_gym/envs/loop_tool/service/loop_tool_compilation_session.py
  compiler_gym/requirements.txt
  docs/source/envs/loop_tool.rst
  docs/source/index.rst
  setup.py
  tests/loop_tool/BUILD
  tests/loop_tool/actions_test.py
Labels: CLA Signed

#433 [ci] Add a codeql workflow for Python.
  .github/workflows/codeql.yaml
Labels: CLA Signed

#424 Add support for running CompilerGym environments from docker containers
  .github/workflows/build.yaml
  Makefile
  compiler_gym/bin/random_search.py
  compiler_gym/bin/service.py
  compiler_gym/datasets/benchmark.py
  compiler_gym/envs/compiler_env.py
  compiler_gym/service/connection.py
  compiler_gym/service/proto/compiler_gym_service.proto
  compiler_gym/util/flags/env_from_flags.py
  packaging/compiler_gym-local-wheel/.gitignore
  packaging/compiler_gym-local-wheel/Dockerfile
  packaging/compiler_gym-manylinux-build/Dockerfile
  packaging/compiler_gym-manylinux-build/container_init.sh
  packaging/compiler_gym/Dockerfile
  tests/bin/manual_env_bin_test.py
  tests/compiler_env_test.py
  tests/datasets/benchmark_test.py
  tests/datasets/files_dataset_test.py
  tests/llvm/custom_benchmarks_test.py
  tests/llvm/llvm_session_parameters_test.py
Labels: CLA Signed

#428 Un-bazel-ify the examples
  .github/workflows/ci.yaml
  BUILD.bazel
  compiler_gym/util/flags/BUILD
  compiler_gym/util/flags/benchmark_from_flags.py
  compiler_gym/util/flags/seed.py
  examples/BUILD
  examples/actor_critic.py
  examples/actor_critic_test.py
  examples/brute_force_test.py
  examples/explore_test.py
  examples/gcc_search.py
  examples/gcc_search_test.py
  examples/makefile_integration/Makefile
  examples/random_walk_test.py
  examples/sensitivity_analysis/BUILD
  examples/sensitivity_analysis/action_sensitivity_analysis.py
  examples/sensitivity_analysis/action_sensitivity_analysis_test.py
  examples/sensitivity_analysis/benchmark_sensitivity_analysis.py
  examples/sensitivity_analysis/benchmark_sensitivity_analysis_test.py
  examples/tabular_q_test.py
Labels: CLA Signed

#430 [env] Fix a bug in reset() failure handling.
  compiler_gym/envs/compiler_env.py
Labels: CLA Signed

#436 Bump the node-notifier version.
  www/frontends/compiler_gym/package-lock.json
Labels: CLA Signed

#441 [README] Improve code sample.
  README.md
Labels: CLA Signed

#444 [ci] Don't fail CI jobs if code coverage upload fails.
  .github/workflows/ci.yaml
Labels: CLA Signed

#440 [ci] Persist the bazel build cache.
  .github/workflows/ci.yaml
Labels: CLA Signed

#435 [util] Increase persistence on "Too many Requests" errors.
  compiler_gym/util/download.py
  tests/util/download_test.py
Labels: CLA Signed

#369 Extend action spaces to be composable and continuous.
  compiler_gym/envs/compiler_env.py
  compiler_gym/envs/gcc/service/BUILD
  compiler_gym/envs/gcc/service/gcc_service.py
  compiler_gym/envs/llvm/BUILD
  compiler_gym/envs/llvm/llvm_env.py
  compiler_gym/envs/llvm/make_specs.py
  compiler_gym/envs/llvm/service/ActionSpace.cc
  compiler_gym/envs/llvm/service/BUILD
  compiler_gym/envs/llvm/service/LlvmSession.cc
  compiler_gym/envs/llvm/service/passes/BUILD
  compiler_gym/envs/llvm/service/passes/make_action_space_genfiles.py
  compiler_gym/envs/loop_tool/service/loop_tool_compilation_session.py
  compiler_gym/service/proto/BUILD
  compiler_gym/service/proto/__init__.py
  compiler_gym/service/proto/compiler_gym_service.proto
  compiler_gym/service/proto/py_converters.py
  compiler_gym/service/runtime/compiler_gym_service.py
  compiler_gym/spaces/BUILD
  compiler_gym/spaces/__init__.py
  compiler_gym/spaces/box.py
  compiler_gym/spaces/commandline.py
  compiler_gym/spaces/dict.py
  compiler_gym/spaces/discrete.py
  compiler_gym/spaces/named_discrete.py
  compiler_gym/spaces/reward.py
  compiler_gym/spaces/scalar.py
  compiler_gym/spaces/sequence.py
  compiler_gym/spaces/tuple.py
  compiler_gym/third_party/autophase/InstCount.cc
  compiler_gym/util/BUILD
  compiler_gym/util/EnumUtil.h
  compiler_gym/views/observation_space_spec.py
  docs/source/cc/compiler_gym/service/runtime.rst
  docs/source/compiler_gym/service.rst
  docs/source/compiler_gym/service/runtime.rst
  docs/source/compiler_gym/spaces.rst
  docs/source/index.rst
  docs/source/rpc.rst
  examples/RandomSearch.cc
  examples/example_compiler_gym_service/env_tests.py
  examples/example_compiler_gym_service/service_cc/ExampleService.cc
  examples/example_compiler_gym_service/service_py/example_service.py
  setup.py
  tests/gcc/gcc_env_test.py
  tests/llvm/BUILD
  tests/llvm/action_space_test.py
  tests/llvm/llvm_env_test.py
  tests/llvm/observation_spaces_test.py
  tests/llvm/service/ActionSpaceTest.cc
  tests/pytest_plugins/llvm.py
  tests/service/proto/BUILD
  tests/service/proto/__init__.py
  tests/service/proto/py_converters_test.py
  tests/spaces/commandline_test.py
  tests/spaces/named_discrete_test.py
  tests/spaces/scalar_test.py
  tests/spaces/sequence_test.py
  tests/util/EnumUtilTest.cc
Labels: CLA Signed

#442 [llvm] Add a new Bitcode observation space.
  compiler_gym/envs/llvm/service/Observation.cc
  compiler_gym/envs/llvm/service/ObservationSpaces.cc
  compiler_gym/envs/llvm/service/ObservationSpaces.h
  compiler_gym/spaces/sequence.py
  tests/llvm/observation_spaces_test.py
  tests/spaces/sequence_test.py
Labels: CLA Signed

#447 [ci] Add a CI job to build the nodejs frontend.
  .github/workflows/ci.yaml
  Makefile
  www/frontends/compiler_gym/package-lock.json
  www/frontends/compiler_gym/package.json
Labels: CLA Signed
