Repository facebookresearch/CompilerGym, pull requests merged in 2022-11, with the labels that each got.

#773 CompilerGym v0.2.5
  .github/workflows/build.yaml
  .github/workflows/ci.yaml
  .github/workflows/codeql.yaml
  .github/workflows/fuzz.yaml
  .github/workflows/pip_install_test.yaml
  .github/workflows/pre_commit.yaml
  CHANGELOG.md
  CITATION.cff
  INSTALL.md
  VERSION
  compiler_gym/datasets/benchmark.py
  compiler_gym/envs/llvm/datasets/BUILD
  compiler_gym/envs/llvm/datasets/CMakeLists.txt
  compiler_gym/envs/llvm/datasets/__init__.py
  compiler_gym/envs/llvm/datasets/jotaibench.py
  compiler_gym/envs/llvm/llvm_env.py
  compiler_gym/envs/llvm/llvm_rewards.py
  compiler_gym/requirements.txt
  compiler_gym/service/client_service_compiler_env.py
  compiler_gym/spaces/named_discrete.py
  compiler_gym/spaces/reward.py
  compiler_gym/spaces/scalar.py
  compiler_gym/util/decorators.py
  docs/requirements.txt
  docs/source/llvm/api.rst
  docs/source/llvm/index.rst
  examples/Makefile
  examples/example_compiler_gym_service/README.md
  examples/example_compiler_gym_service/__init__.py
  examples/example_compiler_gym_service/demo_without_bazel.py
  examples/example_compiler_gym_service/env_tests.py
  examples/example_compiler_gym_service/env_without_bazel_test.py
  examples/requirements.txt
  packaging/compiler_gym-manylinux-build/container_init.sh
  setup.py
  tests/datasets/benchmark_test.py
  tests/llvm/BUILD
  tests/llvm/datasets/BUILD
  tests/llvm/datasets/CMakeLists.txt
  tests/llvm/datasets/jotaibench_test.py
  tests/llvm/datasets/llvm_datasets_test.py
  tests/llvm/datasets_pickle_test.py
  tests/llvm/runtime_test.py
  tests/spaces/named_discrete_test.py
  tests/spaces/scalar_test.py
  tests/validation_result_test.py
  tox.ini
Labels: CLA Signed

#705 Jotaibench
  compiler_gym/envs/llvm/datasets/BUILD
  compiler_gym/envs/llvm/datasets/CMakeLists.txt
  compiler_gym/envs/llvm/datasets/__init__.py
  compiler_gym/envs/llvm/datasets/jotaibench.py
  docs/source/llvm/api.rst
  docs/source/llvm/index.rst
  tests/llvm/datasets/BUILD
  tests/llvm/datasets/CMakeLists.txt
  tests/llvm/datasets/jotaibench_test.py
  tests/llvm/datasets/llvm_datasets_test.py
Labels: CLA Signed

#774 Refactored CVE-2007-4559 Patch
  compiler_gym/envs/llvm/datasets/cbench.py
  compiler_gym/third_party/llvm/__init__.py
  compiler_gym/util/filesystem.py
  examples/gnn_cost_model/train.py
Labels: Bug, CLA Signed

#754 [tests] Minimize the fork regression tests.
  tests/llvm/fork_regression_test.py
Labels: CLA Signed

#772 [llvm] Add utility functions to split and merge benchmarks.
  .github/workflows/ci.yaml
  compiler_gym/datasets/benchmark.py
  compiler_gym/envs/llvm/__init__.py
  compiler_gym/envs/llvm/llvm_benchmark.py
  compiler_gym/envs/llvm/service/BUILD
  compiler_gym/envs/llvm/service/CMakeLists.txt
  compiler_gym/envs/llvm/service/LlvmExtractOne.cc
  compiler_gym/third_party/llvm/BUILD
  compiler_gym/third_party/llvm/CMakeLists.txt
  compiler_gym/third_party/llvm/__init__.py
  docs/source/llvm/api.rst
  setup.py
  tests/llvm/llvm_benchmark_test.py
Labels: CLA Signed, LLVM

#760 [examples] Use PyTorch rllib backend, drop Tensorflow dependency.
  .github/workflows/ci.yaml
  Makefile
  compiler_gym/envs/llvm/llvm_env.py
  compiler_gym/errors/dataset_errors.py
  examples/llvm_rl/config/agent/a2c.yaml
  examples/llvm_rl/config/agent/apex.yaml
  examples/llvm_rl/config/agent/impala.yaml
  examples/llvm_rl/config/agent/ppo.yaml
  examples/requirements.txt
  tests/llvm/custom_benchmarks_test.py
  tests/llvm/datasets/poj104_test.py
  tests/requirements.txt
Labels: CLA Signed
